wip velero

diff --git a/vbash/vkube b/vbash/vkube
--- a/vbash/vkube
+++ b/vbash/vkube
@@ -235,6 +235,12 @@ vkube_k3s_install_usage() {
     echo
 
     # :flag.usage
+    printf "  %s\n" "$(magenta "--velero")"
+    printf "    Velero is an open source tool to safely backup and restore, perform disaster\n    recovery, and migrate Kubernetes cluster resources and persistent volumes.\n"
+    printf "    %s\n" "Conflicts: --storage"
+    echo
+
+    # :flag.usage
     printf "  %s\n" "$(magenta "--csi-driver-nfs")"
     printf "    CSI driver NFS storage. Overriding storage use in cluster plan. Install all\n    if --core, --storage, and --apps flags are not set.\n"
     printf "    %s\n" "Conflicts: --storage"
@@ -249,6 +255,12 @@ vkube_k3s_install_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--csi-synology")"
     printf "    Synology CSI storage (NFS, SMB, ISCSI). Overriding storage use in cluster\n    plan. Install all if --core, --storage, and --apps flags are not set.\n"
+    printf "    %s\n" "Conflicts: --storage"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--csi-driver-direct-pv")"
+    printf "    MinIO Direct PV storage. Overriding storage use in cluster plan. Install all\n    if --core, --storage, and --apps flags are not set.\n"
     printf "    %s\n" "Conflicts: --storage"
     echo
 
@@ -403,8 +415,9 @@ vkube_app_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples:")"
-    printf "  ./vkube busybox --help\n"
-    printf "  ./vkube busybox install mybusybox --synology-csi-plan\n  ../synology-csi-plan.yaml\n"
+    printf "  ./vkube app install busybox --help\n"
+    printf "  ./vkube app install busybox mybusybox --synology-csi-plan\n  ../synology-csi-plan.yaml\n"
+    printf "  ./vkube app install velero velero\n"
     echo
 
   fi
@@ -1360,6 +1373,19 @@ vkube_k3s_install_parse_requirements() {
         ;;
 
       # :flag.case
+      --velero)
+        # :flag.conflicts
+        if [[ -n "${args['--storage']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--storage" >&2
+          exit 1
+        fi
+
+        # :flag.case_no_arg
+        args['--velero']=1
+        shift
+        ;;
+
+      # :flag.case
       --csi-driver-nfs)
         # :flag.conflicts
         if [[ -n "${args['--storage']:-}" ]]; then
@@ -1395,6 +1421,19 @@ vkube_k3s_install_parse_requirements() {
 
         # :flag.case_no_arg
         args['--csi-synology']=1
+        shift
+        ;;
+
+      # :flag.case
+      --csi-driver-direct-pv)
+        # :flag.conflicts
+        if [[ -n "${args['--storage']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--storage" >&2
+          exit 1
+        fi
+
+        # :flag.case_no_arg
+        args['--csi-driver-direct-pv']=1
         shift
         ;;
 
