Revert "wip"
This reverts commit 97ee52a153792b13ba865bb3f8a19cc0a26fb5a5.

# Conflicts:
#	README.md
#	vbash/vkube
#	vbash/vkube-data/k3s-HA/apps/103-gitea/README.md
#	vbash/vkube.prj/src/bashly.yml

diff --git a/vbash/vkube b/vbash/vkube
--- a/vbash/vkube
+++ b/vbash/vkube
@@ -26,8 +26,8 @@ vkube_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
-  printf "  %s   Kubernetes cluster\n" "$(green "cluster")"
-  printf "  %s   Application commands\n" "$(green "app")    "
+  printf "  %s   k3s kubernetes\n" "$(green "k3s") "
+  printf "  %s   Application commands\n" "$(green "app") "
   echo
 
   # :command.long_usage
@@ -119,9 +119,9 @@ vkube_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples:")"
     printf "  ./vkube --help\n"
-    printf "  ./vkube cluster install k3s-ha\n"
-    printf "  ./vkube cluster install ../k3s-ha.yaml\n"
-    printf "  ./vkube cluster backup\n"
+    printf "  ./vkube k3s install k3s-HA\n"
+    printf "  ./vkube k3s install ../k3s-HA.yaml\n"
+    printf "  ./vkube k3s backup\n"
     printf "  ./vkube synology-csi install\n"
     echo
 
@@ -159,12 +159,12 @@ vkube_exec_usage() {
 }
 
 # :command.usage
-vkube_cluster_usage() {
-  printf "vkube cluster - Kubernetes cluster\n\n"
+vkube_k3s_usage() {
+  printf "vkube k3s - k3s kubernetes\n\n"
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  vkube cluster COMMAND\n"
-  printf "  vkube cluster [COMMAND] --help | -h\n"
+  printf "  vkube k3s COMMAND\n"
+  printf "  vkube k3s [COMMAND] --help | -h\n"
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Commands:")"
@@ -172,9 +172,9 @@ vkube_cluster_usage() {
   printf "  %s   Delete cluster kubernetes, storage drivers, applications\n" "$(green "delete")       "
   printf "  %s   Get information\n" "$(green "get")          "
   printf "  %s   Test speed for storage storage class\n" "$(green "storage-speed")"
-  printf "  %s   Upgrade cluster kubernetes\n" "$(green "upgrade")      "
-  printf "  %s   Backup cluster kubernetes\n" "$(green "backup")       "
-  printf "  %s   Restore cluster kubernetes\n" "$(green "restore")      "
+  printf "  %s   Upgrade k3s kubernetes\n" "$(green "upgrade")      "
+  printf "  %s   Backup k3s kubernetes\n" "$(green "backup")       "
+  printf "  %s   Restore k3s kubernetes\n" "$(green "restore")      "
   echo
 
   # :command.long_usage
@@ -214,8 +214,8 @@ vkube_cluster_install_usage() {
   printf "vkube cluster install - Install cluster kubernetes, storage drivers, applications\n\n"
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  vkube cluster install [OPTIONS]\n"
-  printf "  vkube cluster install --help | -h\n"
+  printf "  vkube k3s install [OPTIONS]\n"
+  printf "  vkube k3s install --help | -h\n"
   echo
 
   # :command.long_usage
@@ -501,12 +501,12 @@ vkube_cluster_storage_speed_usage() {
 }
 
 # :command.usage
-vkube_cluster_upgrade_usage() {
-  printf "vkube cluster upgrade - Upgrade cluster kubernetes\n\n"
+vkube_k3s_upgrade_usage() {
+  printf "vkube k3s upgrade - Upgrade k3s kubernetes\n\n"
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  vkube cluster upgrade\n"
-  printf "  vkube cluster upgrade --help | -h\n"
+  printf "  vkube k3s upgrade\n"
+  printf "  vkube k3s upgrade --help | -h\n"
   echo
 
   # :command.long_usage
@@ -522,12 +522,12 @@ vkube_cluster_upgrade_usage() {
 }
 
 # :command.usage
-vkube_cluster_backup_usage() {
-  printf "vkube cluster backup - Backup cluster kubernetes\n\n"
+vkube_k3s_backup_usage() {
+  printf "vkube k3s backup - Backup k3s kubernetes\n\n"
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  vkube cluster backup\n"
-  printf "  vkube cluster backup --help | -h\n"
+  printf "  vkube k3s backup\n"
+  printf "  vkube k3s backup --help | -h\n"
   echo
 
   # :command.long_usage
@@ -543,12 +543,12 @@ vkube_cluster_backup_usage() {
 }
 
 # :command.usage
-vkube_cluster_restore_usage() {
-  printf "vkube cluster restore - Restore cluster kubernetes\n\n"
+vkube_k3s_restore_usage() {
+  printf "vkube k3s restore - Restore k3s kubernetes\n\n"
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  vkube cluster restore\n"
-  printf "  vkube cluster restore --help | -h\n"
+  printf "  vkube k3s restore\n"
+  printf "  vkube k3s restore --help | -h\n"
   echo
 
   # :command.long_usage
@@ -991,7 +991,7 @@ vkube_exec_command() {
 }
 
 # :command.function
-vkube_cluster_install_command() {
+vkube_k3s_install_command() {
 
   # src/cluster_install_command.sh
   #!/usr/bin/env bash
@@ -1087,9 +1087,9 @@ vkube_cluster_upgrade_command() {
 }
 
 # :command.function
-vkube_cluster_backup_command() {
+vkube_k3s_backup_command() {
 
-  # src/cluster_backup_command.sh
+  # src/k3s_backup_command.sh
   echo "# this file is located in 'src/k3s_backup_command.sh'"
   echo "# code for 'vkube k3s backup' goes here"
   echo "# you can edit it freely and regenerate (it will not be overwritten)"
@@ -1098,9 +1098,9 @@ vkube_cluster_backup_command() {
 }
 
 # :command.function
-vkube_cluster_restore_command() {
+vkube_k3s_restore_command() {
 
-  # src/cluster_restore_command.sh
+  # src/k3s_restore_command.sh
   echo "# this file is located in 'src/k3s_restore_command.sh'"
   echo "# code for 'vkube k3s restore' goes here"
   echo "# you can edit it freely and regenerate (it will not be overwritten)"
@@ -1116,15 +1116,15 @@ vkube_app_install_general_command() {
   vlib.bashly-init-command
 
   # shellcheck source=/dev/null
-  source "${VBASH}/vkube-lib.bash"
-  vkube-lib.command-init
+  source "${VBASH}/vkube-k3s.bash"
+  vkube-k3s.command-init
 
   #csi_synology_ver=${args[release]}
   #csi_synology_secret_folder=${args[--secret-folder]}
   #csi_synology_snapshot_use=${args[--snapshot]}
 
-  vkube-lib.check-cluster-plan-path
-  vkube-lib.app-install "${args[container-name]}"
+  vkube-k3s.check-cluster-plan-path
+  vkube-k3s.app-install "${args[container-name]}"
 
 }
 
@@ -1136,15 +1136,15 @@ vkube_app_install_busybox_command() {
   vlib.bashly-init-command
 
   # shellcheck source=/dev/null
-  source "${VBASH}/vkube-lib.bash"
-  vkube-lib.command-init
+  source "${VBASH}/vkube-k3s.bash"
+  vkube-k3s.command-init
 
   #csi_synology_ver=${args[release]}
   #csi_synology_secret_folder=${args[--secret-folder]}
   #csi_synology_snapshot_use=${args[--snapshot]}
 
-  vkube-lib.check-cluster-plan-path
-  vkube-lib.app-install busybox
+  vkube-k3s.check-cluster-plan-path
+  vkube-k3s.app-install busybox
 
 }
 
@@ -1156,15 +1156,15 @@ vkube_app_uninstall_deployment_command() {
   vlib.bashly-init-command
 
   # shellcheck source=/dev/null
-  source "${VBASH}/vkube-lib.bash"
-  vkube-lib.command-init
+  source "${VBASH}/vkube-k3s.bash"
+  vkube-k3s.command-init
 
   #csi_synology_ver=${args[release]}
   #csi_synology_secret_folder=${args[--secret-folder]}
   #csi_synology_snapshot_use=${args[--snapshot]}
 
-  vkube-lib.check-cluster-plan-path
-  vkube-lib.app-deployment-uninstall "${args[general-deployment-name]}"
+  vkube-k3s.check-cluster-plan-path
+  vkube-k3s.app-deployment-uninstall "${args[general-deployment-name]}"
 
 }
 
@@ -1345,10 +1345,10 @@ parse_requirements() {
       shift $#
       ;;
 
-    cluster)
-      action="cluster"
+    k3s)
+      action="k3s"
       shift
-      vkube_cluster_parse_requirements "$@"
+      vkube_k3s_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1453,14 +1453,14 @@ vkube_exec_parse_requirements() {
 }
 
 # :command.parse_requirements
-vkube_cluster_parse_requirements() {
+vkube_k3s_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        vkube_cluster_usage
+        vkube_k3s_usage
         exit
         ;;
 
@@ -1501,34 +1501,34 @@ vkube_cluster_parse_requirements() {
     storage-speed)
       action="storage-speed"
       shift
-      vkube_cluster_storage_speed_parse_requirements "$@"
+      vkube_k3s_storage_speed_parse_requirements "$@"
       shift $#
       ;;
 
     upgrade)
       action="upgrade"
       shift
-      vkube_cluster_upgrade_parse_requirements "$@"
+      vkube_k3s_upgrade_parse_requirements "$@"
       shift $#
       ;;
 
     backup)
       action="backup"
       shift
-      vkube_cluster_backup_parse_requirements "$@"
+      vkube_k3s_backup_parse_requirements "$@"
       shift $#
       ;;
 
     restore)
       action="restore"
       shift
-      vkube_cluster_restore_parse_requirements "$@"
+      vkube_k3s_restore_parse_requirements "$@"
       shift $#
       ;;
 
     # :command.command_fallback
     "")
-      vkube_cluster_usage >&2
+      vkube_k3s_usage >&2
       exit 1
       ;;
 
@@ -1563,14 +1563,14 @@ vkube_cluster_parse_requirements() {
 }
 
 # :command.parse_requirements
-vkube_cluster_install_parse_requirements() {
+vkube_k3s_install_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        vkube_cluster_install_usage
+        vkube_k3s_install_usage
         exit
         ;;
 
@@ -1582,7 +1582,7 @@ vkube_cluster_install_parse_requirements() {
   done
 
   # :command.command_filter
-  action="cluster install"
+  action="k3s install"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2217,7 +2217,7 @@ vkube_cluster_storage_speed_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['storage-class']+x} ]]; then
-    printf "missing required argument: STORAGE-CLASS\nusage: vkube cluster storage-speed STORAGE-CLASS... [OPTIONS]\n" >&2
+    printf "missing required argument: STORAGE-CLASS\nusage: vkube k3s storage-speed STORAGE-CLASS... [OPTIONS]\n" >&2
 
     exit 1
   fi
@@ -2234,14 +2234,14 @@ vkube_cluster_storage_speed_parse_requirements() {
 }
 
 # :command.parse_requirements
-vkube_cluster_upgrade_parse_requirements() {
+vkube_k3s_upgrade_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        vkube_cluster_upgrade_usage
+        vkube_k3s_upgrade_usage
         exit
         ;;
 
@@ -2253,7 +2253,7 @@ vkube_cluster_upgrade_parse_requirements() {
   done
 
   # :command.command_filter
-  action="cluster upgrade"
+  action="k3s upgrade"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2279,14 +2279,14 @@ vkube_cluster_upgrade_parse_requirements() {
 }
 
 # :command.parse_requirements
-vkube_cluster_backup_parse_requirements() {
+vkube_k3s_backup_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        vkube_cluster_backup_usage
+        vkube_k3s_backup_usage
         exit
         ;;
 
@@ -2298,7 +2298,7 @@ vkube_cluster_backup_parse_requirements() {
   done
 
   # :command.command_filter
-  action="cluster backup"
+  action="k3s backup"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2324,14 +2324,14 @@ vkube_cluster_backup_parse_requirements() {
 }
 
 # :command.parse_requirements
-vkube_cluster_restore_parse_requirements() {
+vkube_k3s_restore_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       --help | -h)
         long_usage=yes
-        vkube_cluster_restore_usage
+        vkube_k3s_restore_usage
         exit
         ;;
 
@@ -2343,7 +2343,7 @@ vkube_cluster_restore_parse_requirements() {
   done
 
   # :command.command_filter
-  action="cluster restore"
+  action="k3s restore"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
